
name: ReactAC
version: "1.0.0"

main: com.g4vrk.react.ReactPlugin
api-version: '1.16'

softdepend:
  - packetevents

authors:
  - g4vrk

website: t.me/react_ac

permissions:
  react.alerts:
    default: op
  react.admin:
    default: op

libraries:
  - com.squareup.moshi:moshi:1.15.0
  - com.squareup.moshi:moshi-adapters:1.15.0
  - org.spongepowered:configurate-yaml:4.2.0

