
#
# React - AI-Powered Anti-Cheat
#
# Plugin source code: https://github.com/g4vrk/React
# (The AI model is not included in this project)
#
# Purchase access to our model -> https://www.react-ac.space/
#

# Alert settings
alerts:

  # Show alerts in the console?
  show-in-console: true

  # Chat alert format
  format: "<b><gradient:#eb2544:#ff3655>⚡ ʀᴇᴀᴄᴛ</gradient></b> <gray>»</gray> <color:#eb2544>{player}</color> <white>провалил <color:#eb2544>{check}</color> <gray>{verbose}</gray>"

# Player settings
player:

  # Check Bedrock players?
  check-bedrock-players: false

  # PvP activity settings
  combat:
    # Number of seconds to analyze rotations after a hit
    time: 2s

  # Player data settings
  data:
    # Maximum number of rotations stored for each player
    rotations-buffer-size: 150


