plugins {
    id 'java-library'
}

repositories {
    maven {
        url = "https://repo.extendedclip.com/content/repositories/placeholderapi/"
    }

    maven {
        url = "https://repo.opencollab.dev/main/"
    }

    maven {
        url = "https://repo.opencollab.dev/snapshots/"
    }
}

def dependenciesDir = file("${rootProject.projectDir}/dependencies")

dependencies {

    compileOnly "io.papermc.paper:paper-api:1.18.2-R0.1-SNAPSHOT"

    compileOnly "me.clip:placeholderapi:2.11.6"
    compileOnly "com.github.retrooper:packetevents-spigot:2.13.0"

    compileOnly "com.squareup.moshi:moshi:1.15.0"
    compileOnly "com.squareup.moshi:moshi-adapters:1.15.0"

    implementation "com.squareup.okhttp3:okhttp:4.12.0"

    implementation("com.zaxxer:HikariCP:7.1.0") {
        exclude group: "org.slf4j", module: "slf4j-api"
    }
    implementation "com.h2database:h2:2.4.240"
    implementation("com.mysql:mysql-connector-j:26.7.0") {
        exclude group: "org.slf4j", module: "slf4j-api"
    }
    implementation("org.mongodb:mongodb-driver-sync:5.10.0") {
        exclude group: "org.slf4j", module: "slf4j-api"
    }
    implementation("org.xerial:sqlite-jdbc:3.53.2.1") {
        exclude group: "org.slf4j", module: "slf4j-api"
    }

    compileOnly "org.ejml:ejml-core:0.41"
    compileOnly "org.ejml:ejml-ddense:0.41"
    compileOnly "org.ejml:ejml-simple:0.41"

    compileOnly "io.papermc:paperlib:1.0.8"

    compileOnly "org.spongepowered:configurate-yaml:4.2.0"

    compileOnly "org.incendo:cloud-paper:2.0.0"

    compileOnly "org.geysermc.geyser:api:2.9.0-SNAPSHOT"
    compileOnly "org.geysermc.floodgate:api:2.2.4-SNAPSHOT"

    implementation fileTree(
            dir: dependenciesDir,
            include: [
                    'schedula-common-1.0.0.jar',
                    'FunctionalActions-2.0.0.jar',
                    'FastTextFormatter-1.0.0.jar',
                    'FunctionalConfiguration-1.0.0.jar'
            ]
    )

    testImplementation platform("org.junit:junit-bom:5.13.4")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"

}

tasks.named("test") {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
