plugins {
    id 'java-library'
}

dependencies {

    compileOnly "io.papermc.paper:paper-api:1.18.2-R0.1-SNAPSHOT"

    compileOnly "com.github.retrooper:packetevents-spigot:2.13.0"

    compileOnly "com.squareup.moshi:moshi:1.15.0"
    compileOnly "com.squareup.moshi:moshi-adapters:1.15.0"

    compileOnly "com.squareup.okhttp3:okhttp:4.12.0"

    compileOnly "org.ejml:ejml-core:0.41"
    compileOnly "org.ejml:ejml-ddense:0.41"
    compileOnly "org.ejml:ejml-simple:0.41"

    compileOnly "org.xerial:sqlite-jdbc:3.42.0.0"

    compileOnly "io.papermc:paperlib:1.0.8"

    compileOnly "org.spongepowered:configurate-yaml:4.2.0"

    implementation "org.incendo:cloud-paper:2.0.0"

    implementation "com.g4vrk:FunctionalActions:2.0.0"
    implementation "com.g4vrk:FastTextFormatter:1.0.1"
    implementation "com.g4vrk:FunctionalConfiguration:1.0.0"

}