
#
# React - АнтиЧит основанный на Проверках от Нейросети
#
# Исходный код плагина: https://github.com/g4vrk/React
# (ИИ модель не входит в проект)
#
# Купить доступ к нашей модели -> https://www.react-ac.space/
#

# а и да, я везде оформляю красиво, даже тут :)

name: React
description: "An AI powered Anti-Cheat product, ready for advanced use"
version: ${version}

# noinspection PluginYml,YAMLSchemaValidation
main: ${mainClass}
api-version: '1.16'

folia-supported: true

softdepend:
  - packetevents
  - PlaceholderAPI

authors:
  - g4vrk

website: https://telegram.me/react_ac

permissions:
  react.command.usage:
    default: op
  react.bypass.aim-ai:
    default: false
  react.alerts:
    default: op
  react.admin:
    default: op

libraries:
  - com.squareup.moshi:moshi:1.15.0
  - com.squareup.moshi:moshi-adapters:1.15.0

  - org.spongepowered:configurate-yaml:4.2.0

  - org.ejml:ejml-core:0.41
  - org.ejml:ejml-ddense:0.41
  - org.ejml:ejml-simple:0.41

  - org.xerial:sqlite-jdbc:3.42.0.0

  - org.incendo:cloud-paper:2.0.0

