
ml-server:
  enabled: true

  server-url: "https://api.react-ac.space"
  api-key: "NONE"

  client:

    connect-timeout: 10s
    read-timeout: 10s
    write-timeout: 10s
    call-timeout: 10s

    retry-on-failure: true

    connection-pool:
      max-idle-connections: 5
      keep-alive-duration: 5m

alerts:

  show-in-console: true

player:

  combat:
    time-seconds: 8s

  rotations-buffer-size: 150

actions:
  alerts:
    on-enable:
      - "[message] "
    on-disable:
      - "[message] "
