alerts:

  show-in-console: true

  format: "<b><gradient:#eb2544:#ff3655>⚡ ʀᴇᴀᴄᴛ</gradient></b> <gray>»</gray> <color:#eb2544>{player}</color> <white>провалил <color:#eb2544>{check}</color> <gray>{verbose}</gray>"

player:

  combat:
    time: 8s

  data:
    rotations-buffer-size: 150


