plugins {
    id 'java'
    id 'react.base-conventions'
    id 'react.shadow-conventions'
}

def dependenciesDir = file("${rootProject.projectDir}/dependencies")

dependencies {

    implementation project(":common")

    compileOnly "io.papermc.paper:paper-api:26.2.build.121-stable"

    implementation fileTree(
            dir: dependenciesDir,
            include: [
                    'schedula-folia-1.0.0.jar',
            ]
    )

}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sourceSets {
    main {
        resources {
            srcDir project(":common").file("src/main/resources")
        }
    }
}

processResources {
    inputs.property("mainClass", "com.g4vrk.react.folia.FoliaReactPlugin")
    inputs.property("version", project.version)

    filesMatching("plugin.yml") {
        expand(
                version: project.version,
                mainClass: "com.g4vrk.react.folia.FoliaReactPlugin"
        )
    }
}

jar {
    enabled = false
}

build {
    dependsOn shadowJar
}
