plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.4.2'
}

dependencies {

    implementation project(":common")

    compileOnly "io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT"

}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sourceSets {
    main {
        resources {
            srcDir project(":common").file("src/main/resources")
        }
    }
}

processResources {
    inputs.property("mainClass", "com.g4vrk.react.folia.FoliaReactPlugin")
    inputs.property("version", project.version)

    filesMatching("plugin.yml") {
        expand(
                version: project.version,
                mainClass: "com.g4vrk.react.folia.FoliaReactPlugin"
        )
    }
}

shadowJar {

    archiveBaseName.set("react")
    archiveVersion.set(project.version.toString())
    archiveClassifier.set("folia")

}

jar {
    enabled = false
}

build {
    dependsOn shadowJar
}