plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.4.2'
}

dependencies {

    implementation project(":common")

    compileOnly "io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT"

}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

processResources {
    inputs.property("mainClass", "com.g4vrk.react.folia.FoliaReactPlugin")
    inputs.property("version", project.version)

    filesMatching("plugin.yml") {
        expand(
                version: project.version,
                mainClass: "com.g4vrk.react.paper.ReactPlugin"
        )
    }
}

shadowJar {

    archiveBaseName.set("react")
    archiveVersion.set(project.version.toString())
    archiveClassifier.set("folia")

    relocate 'okhttp3', 'com.g4vrk.react.shadow.okhttp'
    relocate 'okio', 'com.g4vrk.react.shadow.okio'

    relocate 'com.squareup.moshi', 'com.g4vrk.react.shadow.moshi'

    relocate 'org.ejml', 'com.g4vrk.react.shadow.ejml'

    relocate 'org.xerial', 'com.g4vrk.react.shadow.sqlite'

    relocate 'io.papermc.lib', 'com.g4vrk.react.shadow.paperlib'

    relocate 'org.spongepowered.configurate', 'com.g4vrk.react.shadow.configurate'
}

jar {
    enabled = false
}

build {
    dependsOn shadowJar
}