plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.4.2'
}

def dependenciesDir = file("${rootProject.projectDir}/dependencies")

dependencies {

    implementation project(":common")

    compileOnly "io.papermc.paper:paper-api:1.18.2-R0.1-SNAPSHOT"

    implementation fileTree(
            dir: dependenciesDir,
            include: [
                    'schedula-bukkit-1.0.0.jar',
            ]
    )

}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

sourceSets {
    main {
        resources {
            srcDir project(":common").file("src/main/resources")
        }
    }
}

processResources {
    inputs.property("mainClass", "com.g4vrk.react.paper.PaperReactPlugin")
    inputs.property("version", project.version)

    filesMatching("plugin.yml") {
        expand(
                version: project.version,
                mainClass: "com.g4vrk.react.paper.PaperReactPlugin"
        )
    }
}

shadowJar {

    archiveBaseName.set("react")
    archiveVersion.set(project.version.toString())
    archiveClassifier.set("paper")

}

jar {
    enabled = false
}

build {
    dependsOn shadowJar
}